### ISSUE TITLE
Last comment doesn't get highlighted

### ISSUE THREAD

**Issue by SilentException** [easyfuckingpeasy/chrome-reddit-comment-highlights#1]
As far as I can tell, problem is in the for loop here:
https://github.com/easyfuckingpeasy/chrome-reddit-comment-highlights/blob/master/js/content_script.js#L48

Either use <= or < without length-1 :)

BTW, I also opened the same issue on splendidbits/chrome-reddit-comment-highlights because I wasn't sure what's the official repository.

**Comment by aesy** [comment]
Thanks, I updated the loop #ca30e24

I'm on vacation atm, but I will update the extension as soon as I get back.

**Comment by SilentException** [comment]
Cool :+1: 

While you're at it, you might wanna update the link in the extension description in Chrome Web Store.
And also the link when you click on the extension developer website in Chrome itself :)

Enjoy your vacation ;)

**Comment by aesy** [comment]
Thanks for reminding me, I will!
