### ISSUE TITLE
issue with thread and long comment count that load when scrolled to bottom of page

### ISSUE THREAD

**Issue by kinghat** [easyfuckingpeasy/chrome-reddit-comment-highlights#10]
im see that its not working when there are so many comments that RES(?) loads more of them when you scroll to the bottom of the page.

**Comment by aesy** [comment]
Hey, thanks for the report! Weirdly enough I had never thought of that before but you are right, at the moment only comments visible on page load will be highlighted. That's definitely something I'd like to fix though. I was experimenting a little prior to replying and I think I've found a good solution :) I'll make another comment when I've updated the extension!

**Comment by kinghat** [comment]
*not really related to this bug*
you know how RES does that loading thing for child comments as well? that might be a problem too. i wouldnt like it not to do that with the nested/child comments. i dont mind it doing that loading thing for the pages and pages of comments though. i just want that if its going to load a top level comment that it also load everything under it.

**Comment by aesy** [comment]
> i wouldnt like it not to do that with the nested/child comments

Wait, so if I'm understanding you correctly, you would like it to highlight child comments as well? The solution I came up with would solve that as well.

**Comment by kinghat** [comment]
> Wait, so if I'm understanding you correctly, you would like it to highlight child comments as well? The solution I came up with would solve that as well.

ya i figured your fix would also work on those comments as well. i was talking more as whole that i just want it to expand all for the comments it does load. reddit has a feature to load them as you scroll to them but its flaky at best. i want them to just load(expand/show). not sure if this is a reddit thing or a RES thing.

edit: 
looks like reddit only has these settings:
![image](https://cloud.githubusercontent.com/assets/16073360/26522021/a797e89a-42bc-11e7-9789-2608c29d4282.png)

but you can see here the issue is the comments just get stuck loading sometimes:
![image](https://cloud.githubusercontent.com/assets/16073360/26522044/79221f0c-42bd-11e7-9526-c917e4dfd3fd.png)

**Comment by aesy** [comment]
I have uploaded the highlighting fix to the chrome webstore now (as version 1.1.1) so it should get updated within the next few hours. The issue you're having with the comments not loading is, I think, some issue with reddit itself. Next time that happens, open the developer tools and check if the network request fails for whatever reason. You find it here:

![](http://i.imgur.com/1IVGhjL.png)

Tell me about it then and I'll try to make sense of it.

But that's out of scope for this project, so I consider the issue resolved and will close the issue (you can still comment on it even though it's closed).

**Comment by kinghat** [comment]
ty for the fix and communication! btw how are you theming the console? or do chrome themes do that now?

**Comment by aesy** [comment]
If I remember correctly, it's been a feature for the last year or so. You can find it in the dev tools > settings > preferences > appearance > theme! :)
