### ISSUE TITLE
Feature request: Implement synchronization via Chrome's 'chrome.storage' API

### ISSUE THREAD

**Issue by tropicoo** [easyfuckingpeasy/chrome-reddit-comment-highlights#12]
Hi,
I think it would be great to implement a cloud sync of extension data to have ability to see new comments on different PCs (work/home etc.). 

Chrome extensions in such cases use Chrome's [chrome.storage](https://developer.chrome.com/extensions/storage) API.
Thank you.

**Comment by aesy** [comment]
Hey tropicoo,

It's actually already implemented and used by default :-) 
Has it not been syncing data for you?

**Comment by tropicoo** [comment]
Damn I have no words...
It works. I just don't know why I decided it wasn't working.
Please close this issue.
Sorry for inconvenience. :)

**Comment by aesy** [comment]
Hehe, no worries!
