### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by Two-Tone** [easyfuckingpeasy/chrome-reddit-comment-highlights#13]
I decided to move to FF now that version 57 is out and one of the extensions I miss that is this one.  I can install it via Chrome Store Foxified  and it mostly works! The only issue is that Chrome Store Foxified doesn't give access to the options area, which is needed for a nightmode user like I.

**Comment by aesy** [comment]
Hey Two-Tone,

Never heard of Chrome Store Foxified before! I'll look into proper Firefox support at some point, but I'm a bit busy with life at the moment. It shouldn't be too hard though since Firefox now support WebExtensions.

**Comment by aesy** [comment]
In the meantime, if you are the hacky type and know where Chrome Store Foxified stores extension data, this is the value you'd want to edit: `reddit_au_options.usesRES` and set to `true`.

**Comment by randomtomx** [comment]
Would appreciate Firefox support :)

**Comment by aesy** [comment]
The extension is now available for Firefox 52+, 
please create a new issue if it doesn't work for whatever reason.

https://addons.mozilla.org/firefox/addon/reddit-comment-highlights/

**Comment by randomtomx** [comment]
thanks a lot <3
