### ISSUE TITLE
Applying a CSS class to new comments

### ISSUE THREAD

**Issue by jtraub** [easyfuckingpeasy/chrome-reddit-comment-highlights#2]
Hi

I use Reddit Enhancement Suite extension and sometimes I turn on night mode. It changes Reddit appearance to dark colors which is quite handy at nights.

Reddit (Au) Comment Highlights allows to specify only a single color for new comments which makes it hard to use with RES auto night mode: new comments will be either unreadable in normal mode or night mode (see attached image).

After careful consideration, I came to the conclusion that the most flexible solution would be applying a custom CSS class to new comments in a thread.

Of course, it should be mutually exclusive with coloring: the extension either applies a color and a border or a CSS class.

![image](https://cloud.githubusercontent.com/assets/153191/18475575/490edb4c-7a0a-11e6-9e82-2b5c05c0f439.png)

**Comment by jtraub** [comment]
Please let me know if you are willing to consider this feature. I would be happy to try and make a PR

**Comment by splendidbits** [comment]
I have submitted a PR request for this addition. It needs to be fully tested and merged, if @easyfuckingpeasy agrees.

Peace.

**Comment by jtraub** [comment]
@splendidbits sorry, but I do not see how your PR helps to solve the problem

**Comment by aesy** [comment]
I will add a field for custom CSS, I'll get back to you.

Edit: accidentally clicked close.

**Comment by aesy** [comment]
Done! Now a '.highlight' class is added to every '.thing.comment' that's supposed to be highlighted, and it's possible to write custom CSS in the options that get injected into every reddit page. Options page now look like [this](http://i.imgur.com/UVAxqD9.png). 

Is there anything I have missed?

**Comment by splendidbits** [comment]
This is awesome. Nicee.

**Comment by jtraub** [comment]
@easyfuckingpeasy thanks. It looks great!

> Is there anything I have missed?

I don't know. Maybe specifying class name in settings would be helpful to prevent any clashes with other extensions?

**Comment by aesy** [comment]
I [added the ability](http://i.imgur.com/3xCtmC5.png) to specify a custom class name, but only for custom CSS users. I will upload the new version of the extension to the chrome web store in a day or two.

**Comment by splendidbits** [comment]
thanks isak. :-)

**Comment by jtraub** [comment]
@easyfuckingpeasy Hey, sorry to bother you, but for some reason the extension doesn't add custom css class.

Simple `$(".highlight")` call in console returns an empty array. However, if I switch to color pickers everything works fine and I see non-empty arrays upon invocation of `$(".highlight")`

**Comment by aesy** [comment]
@jtraub Researched it, and you are right, it was a stupid mistake on my part. I pushed a fix and updated the extension, it takes an hour or so for the update to go live. Sorry about that!
