### ISSUE TITLE
Extension storage too large for Firefox Sync

### ISSUE THREAD

**Issue by SimonHertoge** [easyfuckingpeasy/chrome-reddit-comment-highlights#20]
Firefox shows this message every time it tries to sync:
![2018-04-30_03-00-26](https://user-images.githubusercontent.com/4460024/39412871-d8010802-4c22-11e8-97c4-b4dcfb5f4c08.png)

This is the error message in the log:
>1525049350766   Sync.Engine.Extension-Storage   ERROR   Syncing {ada26ae8-41ec-4460-936a-790afc2d85c9}: request failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (18727 > 16384 Bytes.) (resource://services-common/kinto-http-client.js:2340:5) JS Stack trace: ServerResponse@kinto-http-client.js:2340:5

Apparently that's the id of this extension.

**Comment by aesy** [comment]
Hey, thanks for the report! There have been some major changes in how the storage works that hasn't been released yet, and it may take a while until that happens due to Reddits recent UI redesign. In the meantime, if you're not using the redesign, go to the settings and reset the cache for the extension to work again, for a while anyway...

I'll get back to you when the storage updates are released.

**Comment by aesy** [comment]
With the next release (v2.0.0), the extension will be aware of storage errors and truncate the data if necessary. 

https://github.com/aesy/reddit-comment-highlights/blob/e8605f71a9fb400963f99cfbca9d07050a15e8fa/src/storage/ThreadHistory.ts#L158-L161

Reopen this issue if this is still a problem.

**Comment by ghost** [comment]
@aesy why these changes were not pushed to add-on stores?

**Comment by aesy** [comment]
@gwarser They were planned for 2.0 which would include support the reddit redesign, but I kinda lost interest in finishing it as I use the old design exclusively. The currently released version will still truncate the storage based on the storage limits, but not on errors. Did you experience this issue? I could make a new release prior to 2.0 that includes the fix.

**Comment by ghost** [comment]
>The currently released version will still truncate the storage based on the storage limits, but not on errors. Did you experience this issue?

Ah, sorry - I've had this issue before, but what I experience now, seems to be different. I don't see sync errors this time, but looks like storage is incorrectly truncated or no longer updated - after few days new threads highlighting is not applied and old thread seems to be stuck on older date. I can create new issue if you like.

**Comment by aesy** [comment]
> after few days new threads highlighting is not applied and old thread seems to be stuck on older date. I can create new issue if you like.

Please do! Add as many details on the issue as possible as I haven't had that issue myself

**Comment by ghost** [comment]
Sorry for creating more noise in this thread. Turns out my issue is probably caused by browser (Firefox) or Reddit itself - I see these incorrectly highlighted threads in sub I moderate, and this does not require this add-on to work.

**Comment by aesy** [comment]
No worries, thanks for letting me know!
