### ISSUE TITLE
Inconsistent comment highlighting (Chrome)

### ISSUE THREAD

**Issue by Trava715** [easyfuckingpeasy/chrome-reddit-comment-highlights#27]
Started happening fairly recently, maybe the last 2-3 months. After visiting a thread with the extension active and returning to it later, no comments are highlighted despite (X new) showing under the thread.

Seems to be related to comment's age - new comments older than few hours are not highlighted but more recent ones ( <1h ago) are highlighted correctly.

11 new comments, latest ones 4-6 hours ago, nothing in the thread is highlighed:
![image](https://user-images.githubusercontent.com/43389722/185851591-b930386e-c58b-46f9-8a56-16a6d8e475b2.png)
![image](https://user-images.githubusercontent.com/43389722/185851760-34a2e197-684f-40b4-a67d-e15766271302.png)

42 new comments, nothing highlighted, newest comment 32 minutes ago:
![image](https://user-images.githubusercontent.com/43389722/185852714-43539b36-fd65-4a6f-8c49-ddbddb35c116.png)

2 new comments, both made few minutes ago:
![image](https://user-images.githubusercontent.com/43389722/185851823-7394b364-d74e-46e4-8d59-044d6f2405b1.png)
![image](https://user-images.githubusercontent.com/43389722/185851862-f9293058-407c-4280-b77d-7eae1db2f413.png)

Both threads are on the same subreddit in case that makes any difference.

Running on Chrome 104.0.5112.102 64bit, extension v1.2.0
If there's anything I could do to help narrow it down more, please let me know.

**Comment by aesy** [comment]
Hey, thanks for the report! Let's look into this.

That `(X new)` count is put there by Reddit Enhancement Suite, not this extension. I don't know how RES works, but I have noticed in the past that it doesn't always seem to reset the count on every visit. This extension resets the highlights on every visit so they aren't always in sync. I don't intend to replicate RES's behaviour so we'll ignore that count.

We can check the internal state of the extension to see if anything seems off. If you're comfortable running a console command, then you can do the following:
* Visit a Reddit thread
* Open the chrome dev tools (`ctrl + shift + i`, or through the browser menu)
* Select the console tab in the dev tools
* Select the first `Reddit (Au) Comment Highlights` entry (red arrow in the picture below)
* Paste the following in the console and press `Enter`:
```js
(() => {
  const currentDate = new Date();
  const currentThread = document.location.pathname.split('/')[4];
    
  if (!currentThread) {
    console.error('You don\'t seem to be in a thread');
  }

  ['local', 'sync'].forEach(storage => {
    chrome.storage[storage].get('reddit_au_threads', data => {
      const thread = data?.reddit_au_threads
        ?.find(thread => thread.id === currentThread);

      if (thread) {
        console.log({ currentDate, currentThread, storage, lastVisited: new Date(thread.timestamp * 1000) });
      }
    });
  });
})();
```
* This will print out the current date, the current thread id, the type of storage used, and the date when the extension think you last visited the thread. All comments made after this date should be highlighted. Check whether this seems to be the case! Also, if you refresh the page and run this command again, the `lastVisited` date should update.

![console-threads](https://user-images.githubusercontent.com/5068689/186038676-4910284d-5b8c-4cbd-8df3-3d61034a6c67.png)

Another thing that you could do is check for errors in the extension:
* Visit a Reddit thread in a tab
* Open the extensions/addons page (`chrome://extensions/`) in another tab
* Press `Details` under `Reddit (Au) Comment Highlights`
* Press `background page` under `Inspect views`. This will open a dev tools window. Go to the console tab if not there already.
* Go to the Reddit thread tab and refresh it
* Check the dev tools window. Was anything printed out in it?

**Comment by Trava715** [comment]
Thanks for the reply. 

>This will print out the current date, the current thread id, the type of storage used, and the date when the extension think you last visited the thread. **All comments made after this date should be highlighted.** 

Last visited seems to give me the timestamp of the current session instead of previous one:
currentDate: Tue Aug 23 2022 01:42:34
lastVisited: Tue Aug 23 2022 01:42:21
The 13 seconds difference between currentDate and lastVisited is how long it took me to open the console and paste the command.
![image](https://user-images.githubusercontent.com/43389722/186044438-164fbfe2-1b36-402d-910c-6792f4621e36.png)

>Check the dev tools window. Was anything printed out in it?
![image](https://user-images.githubusercontent.com/43389722/186044659-f9aa4ea2-5ce5-413a-872b-d48ec6c204dd.png)

In the meantime I tried changing the thread flush frequency from default one week to two weeks in the extension's advanced settings - so far all new comments get highlighted correctly. Maybe that's related in some way?

**Comment by aesy** [comment]
> Last visited seems to give me the timestamp of the current session instead of previous one

Ah yeah, for some reason I didn't think of that (it's late 😄). The lastVisited time seem to update as expected though, so that's good. 

> Maybe that's related in some way?

I tested around a bit and couldn't find anything faulty. Assuming no bugs, that setting shouldn't make a difference for threads less than a week old.

You could try updating the date yourself and refresh the page to see if comments get highlighted correctly:
```js
(() => {
  const currentThread = document.location.pathname.split('/')[4];
  const timestamp = new Date('2022-08-23').valueOf() / 1000;
    
  if (!currentThread) {
    console.error('You don\'t seem to be in a thread');
  }

  ['local', 'sync'].forEach(storage => {
    chrome.storage[storage].get('reddit_au_threads', data => {
      const threads = data?.reddit_au_threads;
      
      if (threads) {
        const thread = threads.find(thread => thread.id === currentThread);

        if (thread) {
          thread.timestamp = timestamp;
        } else {
          thread = { id: currentThread, timestamp };
          threads.push(thread);
        }

        chrome.storage[storage].set({ reddit_au_threads: threads });
      }
    });
  });
})();
```
All comments made after 23/8 00:00 should be highlighted, and then disappear on a second refresh. You can experiment with the date.

**Comment by Trava715** [comment]
Sorry for a late reply. 

As I said in my earlier comment the issue disappeared after changing the thread flush frequency to two weeks and I haven't been able to reproduce it since. I'll close this for now and reopen if I run into it again.
