### ISSUE TITLE
Manifest V3 version of the extension

### ISSUE THREAD

**Issue by Elinron** [easyfuckingpeasy/chrome-reddit-comment-highlights#30]
Chromium based browsers will remove MV2 support in June 2024, so what is going to happen with this very helpful extension? Are we getting the MV3 version? https://developer.chrome.com/blog/resuming-the-transition-to-mv3/

**Comment by aesy** [comment]
Thanks for your kind words! I will make sure to publish a compatible version to Chrome by that time.

**Comment by aesy** [comment]
Manifest v3 support has been added in 9cc44f00b34048bad381a1d1d09688603c9e421d and has been published in version `3.0.0`. It's pending review in the Chrome Web Store and already approved in Firefox.
