### ISSUE TITLE
[Enhancement] Don't mark own comments as "New"

### ISSUE THREAD

**Issue by Two-Tone** [easyfuckingpeasy/chrome-reddit-comment-highlights#5]
The reasoning is that the user had already seen their comment, thus they're not new (in the context of the thread) to them.

**Comment by aesy** [comment]
That's perfectly reasonable, thanks for the suggestion!

I need some time to think of the best way to go about getting the current users' name (`document.querySelector('.user a').innerText` feels dirty). I'll probably upload a fix within a week!

**Comment by Two-Tone** [comment]
Thanks! That was a fast week :P

**Comment by aesy** [comment]
Haha, I couldn't help myself :)
