### ISSUE TITLE
New comments sometimes do not use custom colors

### ISSUE THREAD

**Issue by Two-Tone** [easyfuckingpeasy/chrome-reddit-comment-highlights#9]
I noticed that there are times where new comments will be highlighted, but the extension will ignore the custom colors.  On RES Nightmode, this leaves comments as being unreadable.

**Comment by aesy** [comment]
Hmm, that's weird. Does some comments get properly styled while others don't, all within the same thread? Do you use custom CSS?

**Comment by Two-Tone** [comment]
Not using custom CSS, I had set my colors back when you could do it via hex
codes.  It's can be fairly rare, going 2 or 3 days at a time without seeing
it.  IIRC, it does affect every comment on the page, but I tend to just
immediately refresh when I see it.

**Comment by aesy** [comment]
Ah, I don't know exactly why that happens but it doesn't surprise me because the color picker weren't (at least intentionally) supposed to work with night mode. Currently you'll have to use custom CSS (check the old [readme](https://github.com/easyfuckingpeasy/chrome-reddit-comment-highlights/tree/v1.0.0)), but I've pushed some changes now to support night mode properly! When you get the update (v1.1.0), please report back if it works for you!

**Comment by Two-Tone** [comment]
Will do!  

[I can now say for certain that it does indeed affect all comments on a page.](https://cloud.githubusercontent.com/assets/4342859/25872357/fe19217a-34cf-11e7-8f4a-401cae1a4f90.png) 

Does the new night mode support act as a toggle or just automatically detect night mode?

**Comment by aesy** [comment]
> Does the new night mode support act as a toggle or just automatically detect night mode?

It will switch automatically, you won't have to think of it :)

**Comment by Two-Tone** [comment]
How are you detecting the switch?

**Comment by aesy** [comment]
RES adds a CSS class (`res-nightmode`) to the page when in night mode

**Comment by aesy** [comment]
Any update?

**Comment by Two-Tone** [comment]
I got a yellow new comment a couple days ago, but I only just now went to
the options and told it I'm a nightmode user.  Had no idea it updated.

**Comment by aesy** [comment]
Hehe, try it out for a bit and tell me if it works for you! :)

**Comment by Two-Tone** [comment]
Will do!

**Comment by Two-Tone** [comment]
Still happens! http://i.imgur.com/cmGwprn.png

**Comment by aesy** [comment]
What the hell... What version of the extension are you using? If you go to the options again, does it ask you whether you're a night mode user again? (previously you had to save afterwards for it to actually get saved)

**Comment by Two-Tone** [comment]
Version 1.1.1

Just went into the options, it asked me if I was a nightmode user again.
Said yes and made sure to save.

Another week, here we go :p

**Comment by aesy** [comment]
Sorry to bother you, how about now? :)

**Comment by Two-Tone** [comment]
Not seen any! I'd say that this bug has been fixed!

**Comment by aesy** [comment]
Great, thanks for the help!
